name:  pullrequest_auto

on:
  schedule:
    - cron:  '0 */6 * * *'   
#    - cron:  '*/10 * * * *'   



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: ssh_gen
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.GIT_RSA }}

    - name: Create Auto PR      
      run: |
           curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
           git config --local user.email "noelkev0@gmail.com" &&  git config --local user.name "arita37"
           git config --global hub.protocol ssh
           bin/hub pull-request --base danieltamming:daniel   --head arita37:dev   -m "Auto Sync arita37/Dev"  & \
           bin/hub pull-request --base OmarOsman:dev  --head arita37:dev   -m "Auto Sync arita37/Dev"  & \
           bin/hub pull-request --base infinitiv-ai:dev  --head arita37:dev   -m "Auto Sync arita37/Dev"  & \
           bin/hub pull-request --base souravsingh:Addmodel-ATSPy  --head arita37:dev   -m "Auto Sync arita37/Dev"  & \
           bin/hub pull-request --base Ahmed3bbas:vision   --head arita37:dev   -m "Auto Sync arita37/Dev"  & \

      env:
           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
