name: test_cli
## Command Line testing


on:
  push:
    branches: 
      dev
      
  schedule:
    # * is a special character in YAML so you have to quote this string
    ### Every 3 hours
    - cron:  '0 */23 * * *'      
    # - cron:  '*/1 * * * *'  
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
   
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      

    ##### Log Start  ######################################################
    - name: ssh_gen
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.GIT_RSA }}
                
    - name: log_start
      run: |
           cd /home/runner/work/mlmodels/  && git clone git@github.com:arita37/mlmodels_store.git  &&  ls && pwd
           cd /home/runner/work/mlmodels/mlmodels/
    ########################################################################


      
    #- uses: actions/cache@v1
    #  id: cache
    #  with:
    #    path: ~/.cache/pip
    #    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #    restore-keys: |
    #      ${{ runner.os }}-pip-
   


    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/requirements_fake.txt') }}

          

    - name: Install numpy
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pip install numpy==1.18.2  pillow==6.2.1
      

    - name: Install repo requirements  1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
           pip install -r requirements.txt


    - name: Install repo requirements   2
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        pip install -r requirements_fake.txt


    - name: Install repo
      run: pip install -e . -r requirements.txt  --no-deps


    - name: repo path
      run: python  run_basic_check.py



    ########  Test running for ALL Command Line
    # - uses: franzdiebold@github-env-vars-action@v1.0.0
    - name: cli_test
      # run: ml_test --do test_cli   2>&1 | tee -a  cd /home/runner/work/mlmodels/mlmodels_store/log_test_cli/log_cli_$(date '+%Y-%m-%d-%H-%M')_$GITHUB_SHA.py
      run: ml_test --do test_cli   2>&1 | tee cd /home/runner/work/mlmodels/mlmodels_store/log_test_cli/log_cli.py


    #       run: ml_test --do test_cli   2>&1 | tee -a  cd /home/runner/work/mlmodels/mlmodels_store/log_test_cli/log_$(GITHUB_SHA)_$(date '+%Y-%m-%d_%H-%M-%S-%3N').py
    #- name: log_gitcommit
    #  run: |
    #       cd /home/runner/work/mlmodels/mlmodels_store/
    #       git config --local user.email "noelkev0@gmail.com" 
    #       git config --local user.name "arita37"        
    #       git pull --all   
    #       ls &&  git add --all &&  git commit -m "test_cli" 
    #       git push --all
    #       cd /home/runner/work/mlmodels/mlmodels/



    - name: log_gitcommit
      run: ml_test --do log_remote_push



